/** Extra seed pool — drained before live YouTube search. */
export const reserve = [
  { id: 'DAgdlvowrng', title: 'Main Vohe Masoom Sharma', artist: 'Masoom Sharma', singer: 'Masoom Sharma', era: 'new' },
  { id: 'pbRYp1Wb7cY', title: 'Saaman Saaman Jee Se Lenge Haridwar Mein - Masoom Sharm', artist: 'Masoom Sharma', singer: 'Masoom Sharma', era: 'new' },
  { id: 'l1nkRkcWlqw', title: 'College Kand Masoom Sharma', artist: 'Masoom Sharma', singer: 'Masoom Sharma', era: 'new' },
  { id: 'n4czuaEsukQ', title: 'Pistol Premi Masoom Sharma', artist: 'Masoom Sharma', singer: 'Masoom Sharma', era: 'new' },
  { id: 'Dd3Zqaw5aTw', title: 'Shiv Bahubali Masoom Sharma', artist: 'Masoom Sharma', singer: 'Masoom Sharma', era: 'new' },
  { id: '--YDrVkgh7E', title: 'Hum to Bhole Hain (Full Song) Masoom Sharma, Srishati S', artist: 'Masoom Sharma', singer: 'Masoom Sharma', era: 'new' },
  { id: 'm2DKqCxUHjk', title: 'Bhole Ke Premi (Full Song) Masoom Sharma, Manjeet Mor, ', artist: 'Masoom Sharma', singer: 'Masoom Sharma', era: 'new' },
  { id: 'ZeaqjybbzzM', title: 'WARNING', artist: 'Masoom Sharma', singer: 'Masoom Sharma', era: 'new' },
  { id: 'JUsXZNT_teI', title: 'Darling Amanraj Gill feat. Sapna Chaudhary', artist: 'Amanraj Gill', singer: 'Amanraj Gill', era: 'new' },
  { id: 'CwWoYOA_aQc', title: 'Saadi Bholi Amanraj Gill', artist: 'Amanraj Gill', singer: 'Amanraj Gill', era: 'new' },
  { id: 'uBVslkqNlaA', title: 'Kasht Amanraj Gill', artist: 'Amanraj Gill', singer: 'Amanraj Gill', era: 'new' },
  { id: 'a-9gTgpfzxM', title: 'Amanraj Gill : Current Shiva Choudhary', artist: 'Amanraj Gill', singer: 'Amanraj Gill', era: 'new' },
  { id: 'heLuz8kkQaE', title: 'Bhaga Aale Amanraj Gill', artist: 'Amanraj Gill', singer: 'Amanraj Gill', era: 'new' },
  { id: 'NBbWFVy8PYw', title: 'Protocol Amanraj Gill', artist: 'Amanraj Gill', singer: 'Amanraj Gill', era: 'new' },
  { id: 'zFT5OV-T_bY', title: 'Saadi Bholi Amanraj Gill', artist: 'Amanraj Gill', singer: 'Amanraj Gill', era: 'new' },
  { id: 'wHylew-VGik', title: 'Kasht Amanraj Gill', artist: 'Amanraj Gill', singer: 'Amanraj Gill', era: 'new' },
  { id: 'Llav5_-5idA', title: 'Ghane Gande - Sumit Parta', artist: 'Sumit Parta', singer: 'Sumit Parta', era: 'new' },
  { id: 'SBgtR8r82t0', title: 'Snap - Sumit Parta', artist: 'Sumit Parta', singer: 'Sumit Parta', era: 'new' },
  { id: 'V42F11aGKyI', title: 'Tere Piche Sumit Parta', artist: 'Sumit Parta', singer: 'Sumit Parta', era: 'new' },
  { id: 'fiZizHop8hk', title: 'Why Parta ?', artist: 'Sumit Parta', singer: 'Sumit Parta', era: 'new' },
  { id: 'XdjCLqrWyck', title: 'All About Haryana - Sumit Parta', artist: 'Sumit Parta', singer: 'Sumit Parta', era: 'new' },
  { id: 'C4yB_94CPnE', title: 'Bottle - Sumit Parta Rakhi Lohchab', artist: 'Sumit Parta', singer: 'Sumit Parta', era: 'new' },
  { id: 'JC6GEfjkyqE', title: 'Thaari Bhabhi - थारी भाभी', artist: 'Sumit Parta', singer: 'Sumit Parta', era: 'new' },
  { id: '0U5tQHFaHms', title: 'Saviour - Sumit Parta & Rawme Hooda ft. Isha Sh', artist: 'Sumit Parta', singer: 'Sumit Parta', era: 'new' },
  { id: 'LCU8YgxVPJc', title: '4WD LXY Music ft. Khasa Aala Chahar', artist: 'Khasa Aala Chahar', singer: 'Khasa Aala Chahar', era: 'new' },
  { id: 'C9WSwNGI7oM', title: 'Jaat Bagdo', artist: 'Khasa Aala Chahar', singer: 'Khasa Aala Chahar', era: 'new' },
  { id: 'A7Dk-ixHKjY', title: 'Status Khasa Aala Chahar', artist: 'Khasa Aala Chahar', singer: 'Khasa Aala Chahar', era: 'new' },
  { id: 'gR08f0Yfrqk', title: 'Classic Connection - Music Video', artist: 'Khasa Aala Chahar', singer: 'Khasa Aala Chahar', era: 'new' },
  { id: 'BEI63kGhWaE', title: 'KD DESIROCK - Non Stop HaryanviHaryana Steelers', artist: 'KD', singer: 'KD', era: 'new' },
  { id: 'GX4UPPxhOgA', title: 'My Queen', artist: 'KD', singer: 'KD', era: 'new' },
  { id: '2avvWaU-UBw', title: 'KD DESIROCK : BHOLA INSIDE Mere Bhitar Bhole Tu Bole', artist: 'KD', singer: 'KD', era: 'new' },
  { id: 'KYnjn2bY6zQ', title: 'Same Time : KD DESIROCK', artist: 'KD', singer: 'KD', era: 'new' },
  { id: 'baazuSkbu-c', title: 'GULZAAR CHHANIWALA - SHAMBHU SHAMBHU (', artist: 'Gulzaar Chhaniwala', singer: 'Gulzaar Chhaniwala', era: 'new' },
  { id: 'nxLSAd2MG9c', title: 'Shambhu Shambhu', artist: 'Gulzaar Chhaniwala', singer: 'Gulzaar Chhaniwala', era: 'new' },
  { id: 'KqwE5dDvpWY', title: 'Gulzaar Chhaniwala - Criminal New Haryanvi Song 2026', artist: 'Gulzaar Chhaniwala', singer: 'Gulzaar Chhaniwala', era: 'new' },
  { id: 'rH8i2RPIPK4', title: 'Gulzaar Chhaniwala - Warning: 8K Haryanvi Song', artist: 'Gulzaar Chhaniwala', singer: 'Gulzaar Chhaniwala', era: 'new' },
  { id: '4tquzaEr08k', title: 'AMIT SAINI ROHTAKIYA : Gunde & Jhunde', artist: 'Amit Saini Rohtakiya', singer: 'Amit Saini Rohtakiya', era: 'new' },
  { id: 'jz0seC0uZ8A', title: 'AMIT SAINI ROHTAKIYA : Kaali Gaadi Bintu', artist: 'Amit Saini Rohtakiya', singer: 'Amit Saini Rohtakiya', era: 'new' },
  { id: 'um2DYzCIRAc', title: 'Khokhe Amit Saini Rohtakiya', artist: 'Amit Saini Rohtakiya', singer: 'Amit Saini Rohtakiya', era: 'new' },
  { id: '3DG2go1R8jQ', title: 'Aghori 5 Amit Saini Rohtakiya', artist: 'Amit Saini Rohtakiya', singer: 'Amit Saini Rohtakiya', era: 'new' },
  { id: 'g9eHtAssgg0', title: 'Chill Bintu Pabra', artist: 'Bintu Pabra', singer: 'Bintu Pabra', era: 'new' },
  { id: 'Oyw1Eo21q5k', title: 'Kabze - Bintu Pabra', artist: 'Bintu Pabra', singer: 'Bintu Pabra', era: 'new' },
  { id: 'ZDm6uBWzcis', title: 'Aawas - Music Video', artist: 'Bintu Pabra', singer: 'Bintu Pabra', era: 'new' },
  { id: 'ezdBKbj4loQ', title: 'Bhola Rehnde Bintu Pabra', artist: 'Bintu Pabra', singer: 'Bintu Pabra', era: 'new' },
  { id: '-MwZIPXOapQ', title: 'Tu Chahiye - Ndee Kundu ft. Sonam Malik', artist: 'Ndee Kundu', singer: 'Ndee Kundu', era: 'new' },
  { id: 'Wi52oejQ9Tg', title: '@NdeeKundu Eve With You (Full Video) EP : Day One', artist: 'Ndee Kundu', singer: 'Ndee Kundu', era: 'new' },
  { id: 'X-STW1u8u-w', title: 'Kon Kade Ke : Ndee Kundu', artist: 'Ndee Kundu', singer: 'Ndee Kundu', era: 'new' },
  { id: 'AGoFWy2vqEo', title: 'Rajyan Ki Trah - Bintu Pabra & Ndee Kundu', artist: 'Bintu Pabra', singer: 'Bintu Pabra', era: 'new' },
  { id: 'cZSrWoBMSrg', title: 'Gypsy (Balam Thanedar) - GD Kaur ft. Pranjal Dahiya & D', artist: 'Pranjal Dahiya', singer: 'Pranjal Dahiya', era: 'new' },
  { id: 'WglKFRu0FJs', title: 'Kale Kagaz Amanraj Gill', artist: 'Amanraj Gill', singer: 'Amanraj Gill', era: 'new' },
];
